export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";

export const SIGN_IN_START = "SIGN_IN_START";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";

export const GET_ALL_CATEGORIES_START = "GET_ALL_CATEGORIES_START";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAILED = "GET_ALL_CATEGORIES_FAILED";

export const GET_MENU_ITEMS_START = "GET_MENU_ITEMS_START";
export const GET_MENU_ITEMS_SUCCESS = "GET_MENU_ITEMS_SUCCESS";
export const GET_MENU_ITEMS_FAILED = "GET_MENU_ITEMS_FAILED";

export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_QUANTITY_TO_CART = "UPDATE_QUANTITY_TO_CART";
